from typing import Callable, Any, List

class Limiter:
    def __init__(self, key_func: Callable[..., Any], default_limits: List[str] | None = None) -> None: ...
    def limit(self, limit_value: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

def get_remote_address(request: Any) -> str: ...
