"""Add integrations to SiteSettings

Revision ID: 95069374a6e7
Revises: 2d0b4c1301bd
Create Date: 2026-07-08 20:47:50.001455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95069374a6e7'
down_revision: Union[str, Sequence[str], None] = '2d0b4c1301bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitesettings', sa.Column('mistral_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sitesettings', sa.Column('recaptcha_client_side_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sitesettings', sa.Column('recaptcha_server_side_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sitesettings', sa.Column('ntfy_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitesettings', 'ntfy_topic')
    op.drop_column('sitesettings', 'recaptcha_server_side_key')
    op.drop_column('sitesettings', 'recaptcha_client_side_key')
    op.drop_column('sitesettings', 'mistral_api_key')
    # ### end Alembic commands ###
