"""Add intent to ChatSession

Revision ID: 968625b21b76
Revises: 499685ee795c
Create Date: 2026-07-01 18:40:03.079519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "968625b21b76"
down_revision: Union[str, Sequence[str], None] = "499685ee795c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chatsession",
        sa.Column("intent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatsession", "intent")
    # ### end Alembic commands ###
